/* The following code was generated by JFlex 1.4.3 on 17/04/17 16:37 */

/* Alunos: Marlon Baptista de Quadros */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/04/17 16:37 from the specification file
 * <tt>asdr_lex.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\26\1\27\1\1\1\1\2\0\1\1\16\26\4\0\1\1\3\0"+
    "\1\2\3\0\1\31\1\31\2\0\1\31\1\24\1\30\1\0\12\23"+
    "\7\0\1\5\1\25\1\6\1\25\1\7\1\13\7\25\1\12\1\11"+
    "\2\25\1\4\1\25\1\3\6\25\4\0\1\10\1\0\1\15\2\25"+
    "\1\14\12\25\1\21\1\17\1\25\1\20\1\25\1\16\1\25\1\22"+
    "\4\25\4\0\41\26\2\0\4\25\4\0\1\25\2\0\1\26\7\0"+
    "\1\25\4\0\1\25\5\0\27\25\1\0\37\25\1\0\u01ca\25\4\0"+
    "\14\25\16\0\5\25\7\0\1\25\1\0\1\25\21\0\160\26\5\25"+
    "\1\0\2\25\2\0\4\25\10\0\1\25\1\0\3\25\1\0\1\25"+
    "\1\0\24\25\1\0\123\25\1\0\213\25\1\0\5\26\2\0\236\25"+
    "\11\0\46\25\2\0\1\25\7\0\47\25\7\0\1\25\1\0\55\26"+
    "\1\0\1\26\1\0\2\26\1\0\2\26\1\0\1\26\10\0\33\25"+
    "\5\0\3\25\15\0\5\26\6\0\1\25\4\0\13\26\5\0\53\25"+
    "\37\26\4\0\2\25\1\26\143\25\1\0\1\25\10\26\1\0\6\26"+
    "\2\25\2\26\1\0\4\26\2\25\12\26\3\25\2\0\1\25\17\0"+
    "\1\26\1\25\1\26\36\25\33\26\2\0\131\25\13\26\1\25\16\0"+
    "\12\26\41\25\11\26\2\25\4\0\1\25\5\0\26\25\4\26\1\25"+
    "\11\26\1\25\3\26\1\25\5\26\22\0\31\25\3\26\104\0\1\25"+
    "\1\0\13\25\67\0\33\26\1\0\4\26\66\25\3\26\1\25\22\26"+
    "\1\25\7\26\12\25\2\26\2\0\12\26\1\0\7\25\1\0\7\25"+
    "\1\0\3\26\1\0\10\25\2\0\2\25\2\0\26\25\1\0\7\25"+
    "\1\0\1\25\3\0\4\25\2\0\1\26\1\25\7\26\2\0\2\26"+
    "\2\0\3\26\1\25\10\0\1\26\4\0\2\25\1\0\3\25\2\26"+
    "\2\0\12\26\4\25\7\0\1\25\5\0\3\26\1\0\6\25\4\0"+
    "\2\25\2\0\26\25\1\0\7\25\1\0\2\25\1\0\2\25\1\0"+
    "\2\25\2\0\1\26\1\0\5\26\4\0\2\26\2\0\3\26\3\0"+
    "\1\26\7\0\4\25\1\0\1\25\7\0\14\26\3\25\1\26\13\0"+
    "\3\26\1\0\11\25\1\0\3\25\1\0\26\25\1\0\7\25\1\0"+
    "\2\25\1\0\5\25\2\0\1\26\1\25\10\26\1\0\3\26\1\0"+
    "\3\26\2\0\1\25\17\0\2\25\2\26\2\0\12\26\1\0\1\25"+
    "\17\0\3\26\1\0\10\25\2\0\2\25\2\0\26\25\1\0\7\25"+
    "\1\0\2\25\1\0\5\25\2\0\1\26\1\25\7\26\2\0\2\26"+
    "\2\0\3\26\10\0\2\26\4\0\2\25\1\0\3\25\2\26\2\0"+
    "\12\26\1\0\1\25\20\0\1\26\1\25\1\0\6\25\3\0\3\25"+
    "\1\0\4\25\3\0\2\25\1\0\1\25\1\0\2\25\3\0\2\25"+
    "\3\0\3\25\3\0\14\25\4\0\5\26\3\0\3\26\1\0\4\26"+
    "\2\0\1\25\6\0\1\26\16\0\12\26\11\0\1\25\7\0\3\26"+
    "\1\0\10\25\1\0\3\25\1\0\27\25\1\0\12\25\1\0\5\25"+
    "\3\0\1\25\7\26\1\0\3\26\1\0\4\26\7\0\2\26\1\0"+
    "\2\25\6\0\2\25\2\26\2\0\12\26\22\0\2\26\1\0\10\25"+
    "\1\0\3\25\1\0\27\25\1\0\12\25\1\0\5\25\2\0\1\26"+
    "\1\25\7\26\1\0\3\26\1\0\4\26\7\0\2\26\7\0\1\25"+
    "\1\0\2\25\2\26\2\0\12\26\1\0\2\25\17\0\2\26\1\0"+
    "\10\25\1\0\3\25\1\0\51\25\2\0\1\25\7\26\1\0\3\26"+
    "\1\0\4\26\1\25\10\0\1\26\10\0\2\25\2\26\2\0\12\26"+
    "\12\0\6\25\2\0\2\26\1\0\22\25\3\0\30\25\1\0\11\25"+
    "\1\0\1\25\2\0\7\25\3\0\1\26\4\0\6\26\1\0\1\26"+
    "\1\0\10\26\22\0\2\26\15\0\60\25\1\26\2\25\7\26\4\0"+
    "\10\25\10\26\1\0\12\26\47\0\2\25\1\0\1\25\2\0\2\25"+
    "\1\0\1\25\2\0\1\25\6\0\4\25\1\0\7\25\1\0\3\25"+
    "\1\0\1\25\1\0\1\25\2\0\2\25\1\0\4\25\1\26\2\25"+
    "\6\26\1\0\2\26\1\25\2\0\5\25\1\0\1\25\1\0\6\26"+
    "\2\0\12\26\2\0\4\25\40\0\1\25\27\0\2\26\6\0\12\26"+
    "\13\0\1\26\1\0\1\26\1\0\1\26\4\0\2\26\10\25\1\0"+
    "\44\25\4\0\24\26\1\0\2\26\5\25\13\26\1\0\44\26\11\0"+
    "\1\26\71\0\53\25\24\26\1\25\12\26\6\0\6\25\4\26\4\25"+
    "\3\26\1\25\3\26\2\25\7\26\3\25\4\26\15\25\14\26\1\25"+
    "\17\26\2\0\46\25\1\0\1\25\5\0\1\25\2\0\53\25\1\0"+
    "\u014d\25\1\0\4\25\2\0\7\25\1\0\1\25\1\0\4\25\2\0"+
    "\51\25\1\0\4\25\2\0\41\25\1\0\4\25\2\0\7\25\1\0"+
    "\1\25\1\0\4\25\2\0\17\25\1\0\71\25\1\0\4\25\2\0"+
    "\103\25\2\0\3\26\40\0\20\25\20\0\125\25\14\0\u026c\25\2\0"+
    "\21\25\1\0\32\25\5\0\113\25\3\0\3\25\17\0\15\25\1\0"+
    "\4\25\3\26\13\0\22\25\3\26\13\0\22\25\2\26\14\0\15\25"+
    "\1\0\3\25\1\0\2\26\14\0\64\25\40\26\3\0\1\25\3\0"+
    "\2\25\1\26\2\0\12\26\41\0\3\26\2\0\12\26\6\0\130\25"+
    "\10\0\51\25\1\26\1\25\5\0\106\25\12\0\35\25\3\0\14\26"+
    "\4\0\14\26\12\0\12\26\36\25\2\0\5\25\13\0\54\25\4\0"+
    "\21\26\7\25\2\26\6\0\12\26\46\0\27\25\5\26\4\0\65\25"+
    "\12\26\1\0\35\26\2\0\13\26\6\0\12\26\15\0\1\25\130\0"+
    "\5\26\57\25\21\26\7\25\4\0\12\26\21\0\11\26\14\0\3\26"+
    "\36\25\15\26\2\25\12\26\54\25\16\26\14\0\44\25\24\26\10\0"+
    "\12\26\3\0\3\25\12\26\44\25\122\0\3\26\1\0\25\26\4\25"+
    "\1\26\4\25\3\26\2\25\11\0\300\25\47\26\25\0\4\26\u0116\25"+
    "\2\0\6\25\2\0\46\25\2\0\6\25\2\0\10\25\1\0\1\25"+
    "\1\0\1\25\1\0\1\25\1\0\37\25\2\0\65\25\1\0\7\25"+
    "\1\0\1\25\3\0\3\25\1\0\7\25\3\0\4\25\2\0\6\25"+
    "\4\0\15\25\5\0\3\25\1\0\7\25\16\0\5\26\32\0\5\26"+
    "\20\0\2\25\23\0\1\25\13\0\5\26\5\0\6\26\1\0\1\25"+
    "\15\0\1\25\20\0\15\25\3\0\33\25\25\0\15\26\4\0\1\26"+
    "\3\0\14\26\21\0\1\25\4\0\1\25\2\0\12\25\1\0\1\25"+
    "\3\0\5\25\6\0\1\25\1\0\1\25\1\0\1\25\1\0\4\25"+
    "\1\0\13\25\2\0\4\25\5\0\5\25\4\0\1\25\21\0\51\25"+
    "\u0a77\0\57\25\1\0\57\25\1\0\205\25\6\0\4\25\3\26\2\25"+
    "\14\0\46\25\1\0\1\25\5\0\1\25\2\0\70\25\7\0\1\25"+
    "\17\0\1\26\27\25\11\0\7\25\1\0\7\25\1\0\7\25\1\0"+
    "\7\25\1\0\7\25\1\0\7\25\1\0\7\25\1\0\7\25\1\0"+
    "\40\26\57\0\1\25\u01d5\0\3\25\31\0\11\25\6\26\1\0\5\25"+
    "\2\0\5\25\4\0\126\25\2\0\2\26\2\0\3\25\1\0\132\25"+
    "\1\0\4\25\5\0\51\25\3\0\136\25\21\0\33\25\65\0\20\25"+
    "\u0200\0\u19b6\25\112\0\u51cd\25\63\0\u048d\25\103\0\56\25\2\0\u010d\25"+
    "\3\0\20\25\12\26\2\25\24\0\57\25\1\26\4\0\12\26\1\0"+
    "\31\25\7\0\1\26\120\25\2\26\45\0\11\25\2\0\147\25\2\0"+
    "\4\25\1\0\4\25\14\0\13\25\115\0\12\25\1\26\3\25\1\26"+
    "\4\25\1\26\27\25\5\26\20\0\1\25\7\0\64\25\14\0\2\26"+
    "\62\25\21\26\13\0\12\26\6\0\22\26\6\25\3\0\1\25\4\0"+
    "\12\26\34\25\10\26\2\0\27\25\15\26\14\0\35\25\3\0\4\26"+
    "\57\25\16\26\16\0\1\25\12\26\46\0\51\25\16\26\11\0\3\25"+
    "\1\26\10\25\2\26\2\0\12\26\6\0\27\25\3\0\1\25\1\26"+
    "\4\0\60\25\1\26\1\25\3\26\2\25\2\26\5\25\2\26\1\25"+
    "\1\26\1\25\30\0\3\25\2\0\13\25\5\26\2\0\3\25\2\26"+
    "\12\0\6\25\2\0\6\25\2\0\6\25\11\0\7\25\1\0\7\25"+
    "\221\0\43\25\10\26\1\0\2\26\2\0\12\26\6\0\u2ba4\25\14\0"+
    "\27\25\4\0\61\25\u2104\0\u016e\25\2\0\152\25\46\0\7\25\14\0"+
    "\5\25\5\0\1\25\1\26\12\25\1\0\15\25\1\0\5\25\1\0"+
    "\1\25\1\0\2\25\1\0\2\25\1\0\154\25\41\0\u016b\25\22\0"+
    "\100\25\2\0\66\25\50\0\15\25\3\0\20\26\20\0\7\26\14\0"+
    "\2\25\30\0\3\25\31\0\1\25\6\0\5\25\1\0\207\25\2\0"+
    "\1\26\4\0\1\25\13\0\12\26\7\0\32\25\4\0\1\25\1\0"+
    "\32\25\13\0\131\25\3\0\6\25\2\0\6\25\2\0\6\25\2\0"+
    "\3\25\3\0\2\25\3\0\2\25\22\0\3\26\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\4\3\1\4\1\5\3\3\1\4"+
    "\1\0\3\3\2\4\1\3\1\6\1\3\1\0\1\3"+
    "\1\7\1\10\3\3\1\11\1\3\1\12";

  private static int [] zzUnpackAction() {
    int [] result = new int[32];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\32\0\64\0\116\0\150\0\202\0\234\0\266"+
    "\0\32\0\320\0\352\0\u0104\0\u011e\0\u0138\0\u0152\0\u016c"+
    "\0\u0186\0\u01a0\0\u01ba\0\u01d4\0\150\0\u01ee\0\u0208\0\u0222"+
    "\0\150\0\32\0\u023c\0\u0256\0\u0270\0\150\0\u028a\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[32];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\11\5\1\6\2\5\1\7\3\5"+
    "\1\10\1\2\1\5\1\2\1\3\2\11\33\0\1\3"+
    "\25\0\1\3\4\0\1\5\1\12\20\5\1\0\3\5"+
    "\4\0\22\5\1\0\3\5\4\0\13\5\1\13\6\5"+
    "\1\0\3\5\4\0\16\5\1\14\3\5\1\0\3\5"+
    "\25\0\1\15\4\0\1\16\3\0\2\5\1\17\17\5"+
    "\1\0\3\5\4\0\14\5\1\20\5\5\1\0\3\5"+
    "\4\0\17\5\1\21\2\5\1\0\3\5\25\0\1\22"+
    "\4\0\1\16\24\0\1\23\10\0\3\5\1\24\16\5"+
    "\1\0\3\5\4\0\13\5\1\25\6\5\1\0\3\5"+
    "\4\0\20\5\1\26\1\5\1\0\3\5\25\0\1\23"+
    "\1\27\3\0\1\16\24\0\1\23\4\0\1\16\3\0"+
    "\4\5\1\30\15\5\1\0\3\5\4\0\13\5\1\31"+
    "\6\5\1\0\3\5\25\0\1\32\10\0\5\5\1\33"+
    "\14\5\1\0\3\5\4\0\6\5\1\34\13\5\1\0"+
    "\3\5\4\0\7\5\1\35\12\5\1\0\3\5\4\0"+
    "\10\5\1\36\1\37\10\5\1\0\3\5\4\0\11\5"+
    "\1\40\10\5\1\0\3\5\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[676];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\4\1\1\0\10\1\1\0"+
    "\2\1\1\11\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[32];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private int comment_count = 0;

  private AsdrSample yyparser;

  public Yylex(java.io.Reader r, AsdrSample yyparser) {
    this(r);
    this.yyparser = yyparser;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2216) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { yyparser.setDebug(true);
          }
        case 11: break;
        case 4: 
          { return AsdrSample.NUM;
          }
        case 12: break;
        case 8: 
          { return AsdrSample.MATR;
          }
        case 13: break;
        case 5: 
          { return yytext().charAt(0);
          }
        case 14: break;
        case 7: 
          { return AsdrSample.PROVA;
          }
        case 15: break;
        case 1: 
          { System.out.println("Erro lexico: caracter invalido: <" + yytext() + ">");
          }
        case 16: break;
        case 3: 
          { return AsdrSample.IDENT;
          }
        case 17: break;
        case 10: 
          { yyparser.setDebug(false);
          }
        case 18: break;
        case 2: 
          { 
          }
        case 19: break;
        case 6: 
          { return AsdrSample.DATA;
          }
        case 20: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
